# Mode
mode: "Train"

# Directories
cache_dir: "/home/ubuntu/scgenai/examples/tmp/cache" ## cache dir to save the model template files
model_dir: "/home/ubuntu/scgenai/examples/testrun/test1/" ## output model dir
log_dir: "/home/ubuntu/scgenai/examples/logs/"

#### Input data files ####
train_file: "/home/ubuntu/scgenai/examples/data/example_train_RNA.h5ad"
val_file: "/home/ubuntu/scgenai/examples/data/example_val_RNA.h5ad"
train_ADTfile: "/home/ubuntu/scgenai/examples/data/example_train_ADT.h5ad"
val_ADTfile: "/home/ubuntu/scgenai/examples/data/example_val_ADT.h5ad"


########################################### General setting ####################################################
savelog: "Yes"
target_feature: "celltype.l2"  # Target name for prediction
num_bins: 10  # Bins for gene expression discretization

########## Model template and context method setting #########
model_backbone_name: "llama" ### "llama", "gpt", "bigbird", "scgent"
model_backbone_size: "small" ### "small", "normal", "large". Suggest "small" for llama
max_length: 5120 
context_method: "random"
multiomics: "Yes"  # Trigger the multiomics method when set to Yes

########################################### Other settings ####################################################
depth: 2  # suggest 2
min_cells: 2  # suggest 50
batch_size: 1 # set this based on GPU memory, higher batch_size higher training speed, but also much more GPU memory will be used
learning_rate: 1e-5  # suggest 1e-5
num_epochs: 20  # suggest 30

