# Mode
mode: "Train"

# Directories
cache_dir: "/home/ubuntu/scgenai/examples/tmp/cache" ## cache dir to save the model template files
model_dir: "/home/ubuntu/scgenai/examples/testrun/test1/" ## output model dir
log_dir: "/home/ubuntu/scgenai/examples/logs/"

#### Input data files 40 cells toy data ####
train_file: "/home/ubuntu/scgenai/examples/data/example_train.h5ad"
val_file: "/home/ubuntu/scgenai/examples/data/example_val.h5ad" ## Optional 
gmtfile: "/home/ubuntu/scgenai/examples/data/c8.BONE_MARROW.v2023.2.Hs.symbols.gmt"

########################################### General setting ####################################################
savelog: "Yes"
target_feature: "ct"  # Target name for prediction
num_bins: 10  # Bins for gene expression discretization

########## Model template and context method setting #########
model_backbone_name: "llama" ### "llama", "gpt", "bigbird", "scgent"
model_backbone_size: "small" ### "small", "normal", "large". Suggest "small" for llama
max_length: 1024 
context_method: "biofounction"
depth: 2 # suggest 2

########################################### Other settings ####################################################
min_cells: 2  # suggest 50
batch_size: 1 # set this based on GPU memory, higher batch_size higher training speed, but also much more GPU memory will be used
learning_rate: 1e-5  # suggest 1e-5
num_epochs: 20  # suggest 30

