# Mode
mode: "Finetune"

# Directories
cache_dir: "/home/ubuntu/scgenai/examples/tmp/cache" ## cache dir to save the model template files
model_dir: "/home/ubuntu/scgenai/examples/testrun/test_random/best_model/" ## output model dir
finetune_dir: "/home/ubuntu/scgenai/examples/testrun/test1/"
log_dir: "/home/ubuntu/scgenai/examples/logs/"

#### Input data files 40 cells toy data ####
train_file: "/home/ubuntu/scgenai/examples/data/example_fintunetrain.h5ad"
val_file: "/home/ubuntu/scgenai/examples/data/example_fintuneval.h5ad" # optional

########################################### General setting ####################################################
savelog: "Yes"
target_feature: "ct"  # Target name for prediction

########################################### Other settings ####################################################
num_epochs: 20  

