# Mode
mode: "Finetune"

# Directories
cache_dir: "/home/ubuntu/scgenai/examples/tmp/cache" ## cache dir to save the model template files
model_dir: "/home/ubuntu/fulldataset/model/GSE181989BW_random_context/best_model/" ## output model dir
finetune_dir: "/home/ubuntu/fulldataset/model/Finetune_GSE135194BW/"
log_dir: "/home/ubuntu/scgenai/examples/logs/"

#### Input data files 40 cells toy data ####
train_file: "/home/ubuntu/fulldataset/GSE135194_train.h5ad"
val_file: "/home/ubuntu/fulldataset/BoneMarrowRefine2_val.h5ad" # optional

########################################### General setting ####################################################
savelog: "Yes"
target_feature: "ct"  # Target name for prediction

########################################### Other settings ####################################################
num_epochs: 30  

