# Mode
mode: "Finetune"

# Directories
cache_dir: "/path_to_your_cache_dir/cache" ## cache dir to save the model template files
model_dir: "/path_to_your_output_model_dir/best_model/" ## pretrained model dir
finetune_dir: "/path_to_your_output_model_dir/" ## output fine-tune model dir
log_dir: "/path_to_your_log_dir/logs/"

#### Input data files ####
train_file: "/path_to_your_finetune_trainfile/finetune_trainfile.h5ad"
val_file: "/path_to_your_finetune_valfile/finetune_valfile.h5ad" ## Optional 

########################################### General setting ####################################################
savelog: "Yes"
target_feature: "ct"  # Target name for prediction

########################################### Other settings ####################################################
num_epochs: 20  # suggest 15-30

